# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ;zoom
    replace: |
      Join Zoom Meeting
      https://utexas.zoom.us/j/9602251508
      Meeting ID:  960 225 1508

  - trigger: ;eadd
    replace: "- trigger:\nreplace:"

  - trigger: ;git
    replace: git pull && git add . && git commit -m '$|$' && git push

  # Dynamic Matches

  - trigger: ";dd"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  - trigger: ";dt"
    replace: "{{mytime}}"
    vars:
      - name: mytime
        type: date
        params:
          format: "%H:%M"
  # And much more! For more information, visit the docs: https://espanso.org/docs/
